-- =========================================================
-- Lab 3 : Execute DML SQL Statements
-- =========================================================

------------------------------------------------------------
-- Step 1: Create Tables
------------------------------------------------------------

-- CLIENT_MASTER Table
CREATE TABLE CLIENT_MASTER (
    CLIENTNO VARCHAR(6) UNIQUE NOT NULL,
    NAME VARCHAR(7) UNIQUE NOT NULL,
    ADDRESS1 VARCHAR(30),
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(15),
    PINCODE NUMERIC(6),
    STATE VARCHAR(15),
    BALDUE NUMERIC(10,2)
);

-- PRODUCT_MASTER Table
CREATE TABLE PRODUCT_MASTER (
    PRODUCTNO VARCHAR(6),
    DESCRIPTION VARCHAR(15),
    PROFITPERCENT NUMERIC(4,2),
    UNITMEASURE VARCHAR(10),
    QTYONHAND NUMERIC(8),
    REORDERLVL NUMERIC(8),
    SELLPRICE NUMERIC(8,2),
    COSTPRICE NUMERIC(8,2)
);

-- SALESMAN_MASTER Table
CREATE TABLE SALESMAN_MASTER (
    SALESMANNO VARCHAR(6),
    SALESMANNAME VARCHAR(20),
    ADDRESS1 VARCHAR(30),
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(20),
    PINCODE NUMERIC(6),
    STATE VARCHAR(20),
    SALAMT NUMERIC(8,2),
    TGTTOGET NUMERIC(6,2),
    YTDSALES NUMERIC(6,2),
    REMARKS VARCHAR(60)
);

------------------------------------------------------------
-- Step 2: Insert Sample Data
------------------------------------------------------------

-- CLIENT_MASTER Data
INSERT INTO CLIENT_MASTER VALUES('1Y093','DARSHAN','SHASTRI MEDAIN','VIDYANAGAR','ANAND',360005,'GUJARAT',122.45);
INSERT INTO CLIENT_MASTER VALUES('12T53','HEER','GANDHI MEDAIN','GANDHINAGAR','AHMADABAD',387625,'TAMILNADU',950.45);
INSERT INTO CLIENT_MASTER VALUES('56087','KRISH','SHIVAM MEDAIN','PUNE','MUMBAI',282425,'MAHARASHTRA',91556.54);

-- PRODUCT_MASTER Data
INSERT INTO PRODUCT_MASTER VALUES('24R45','LAPTOP',25,'KILO',165,7,32543.76,4546.65);
INSERT INTO PRODUCT_MASTER VALUES('42R45','MOBILE',20,'KG',100,8,564.56,415.96);
INSERT INTO PRODUCT_MASTER VALUES('25R45','TV',15,'INCHES',500,9,856.16,52.95);

-- SALESMAN_MASTER Data
INSERT INTO SALESMAN_MASTER VALUES('CP020','DARSHAN','TCS','NANDEL_CHOCK','RAJKOT',360005,'GUJARAT',62000.50,2555,7547,'GOOD');
INSERT INTO SALESMAN_MASTER VALUES('CP071','HEER','MICROSOFT','KRISHNA_CHOCK','SURAT',352013,'GUJARAT',27000.50,2465,9568,'VERY_GOOD');
INSERT INTO SALESMAN_MASTER VALUES('CP001','KRISH','GOOGLE','RAJ_CHOCK','MUMBAI',384512,'MAHARASHTRA',3500,8655,5656,'EXCELLENT');

------------------------------------------------------------
-- Step 3: DML SQL Statements
------------------------------------------------------------

-- 1) SELECT Statement
SELECT * FROM CLIENT_MASTER;
SELECT NAME, CITY FROM CLIENT_MASTER;

-- 2) INSERT Statement
INSERT INTO CLIENT_MASTER VALUES('1X111', 'ANITA', 'MAIN STREET', 'BLOCK A', 'VADODARA', 390001, 'GUJARAT', 500.00);

-- 3) WHERE Clause
SELECT * FROM CLIENT_MASTER WHERE STATE = 'GUJARAT';
SELECT * FROM PRODUCT_MASTER WHERE SELLPRICE > 1000;

-- 4) ORDER BY (Ascending and Descending)
SELECT * FROM CLIENT_MASTER ORDER BY NAME ASC;
SELECT * FROM PRODUCT_MASTER ORDER BY SELLPRICE DESC;

-- 5) Create Table from Existing Table (with data)
CREATE TABLE CLIENT_GUJARAT AS
SELECT * FROM CLIENT_MASTER WHERE STATE = 'GUJARAT';

-- 6) Create Table from Existing Table (without data)
CREATE TABLE PRODUCT_EMPTY AS
SELECT * FROM PRODUCT_MASTER WHERE 1=0;

-- 7) DELETE Statement
DELETE FROM SALESMAN_MASTER WHERE CITY = 'MUMBAI';

-- 8) UPDATE Statement
UPDATE CLIENT_MASTER SET BALDUE = BALDUE + 100 WHERE CLIENTNO = '1Y093';
UPDATE PRODUCT_MASTER SET SELLPRICE = 900.00 WHERE DESCRIPTION = 'TV';

-- =========================================================
-- End of Lab 3 SQL File
-- =========================================================
