-- =========================================================
-- Lab 5 : Apply Data Constraints to Relations
-- Using CLIENT_MASTER, PRODUCT_MASTER, SALESMAN_MASTER
-- =========================================================

------------------------------------------------------------
-- Step 1: Create Tables with Constraints
------------------------------------------------------------

-- CLIENT_MASTER with Primary Key & Not Null
CREATE TABLE CLIENT_MASTER (
    CLIENTNO VARCHAR(6) CONSTRAINT PK_CLIENT PRIMARY KEY,
    NAME VARCHAR(20) CONSTRAINT NN_CLIENTNAME NOT NULL UNIQUE,
    ADDRESS1 VARCHAR(30),
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(15),
    PINCODE NUMERIC(6),
    STATE VARCHAR(15),
    BALDUE NUMERIC(10,2)
);

-- PRODUCT_MASTER with Primary Key & Unique
CREATE TABLE PRODUCT_MASTER (
    PRODUCTNO VARCHAR(6) CONSTRAINT PK_PRODUCT PRIMARY KEY,
    DESCRIPTION VARCHAR(30) CONSTRAINT UQ_DESCRIPTION UNIQUE,
    PROFITPERCENT NUMERIC(4,2),
    UNITMEASURE VARCHAR(10),
    QTYONHAND NUMERIC(8),
    REORDERLVL NUMERIC(8),
    SELLPRICE NUMERIC(8,2) CONSTRAINT NN_SELLPRICE NOT NULL,
    COSTPRICE NUMERIC(8,2)
);

-- SALESMAN_MASTER with Foreign Key (REFERENCES CLIENT_MASTER)
CREATE TABLE SALESMAN_MASTER (
    SALESMANNO VARCHAR(6) CONSTRAINT PK_SALESMAN PRIMARY KEY,
    SALESMANNAME VARCHAR(20) NOT NULL,
    ADDRESS1 VARCHAR(30),
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(20),
    PINCODE NUMERIC(6),
    STATE VARCHAR(20),
    SALAMT NUMERIC(8,2),
    TGTTOGET NUMERIC(6,2),
    YTDSALES NUMERIC(6,2),
    REMARKS VARCHAR(60),
    CLIENTNO VARCHAR(6),
    CONSTRAINT FK_CLIENT FOREIGN KEY (CLIENTNO)
        REFERENCES CLIENT_MASTER(CLIENTNO)
        ON DELETE CASCADE
);

------------------------------------------------------------
-- Step 2: Insert Data
------------------------------------------------------------

-- Insert Clients
INSERT INTO CLIENT_MASTER VALUES('1Y093','DARSHAN','SHASTRI MEDAIN','VIDYANAGAR','ANAND',360005,'GUJARAT',122.45);
INSERT INTO CLIENT_MASTER VALUES('12T53','HEER','GANDHI MEDAIN','GANDHINAGAR','AHMADABAD',387625,'TAMILNADU',950.45);
INSERT INTO CLIENT_MASTER VALUES('56087','KRISH','SHIVAM MEDAIN','PUNE','MUMBAI',282425,'MAHARASHTRA',91556.54);

-- Insert Products
INSERT INTO PRODUCT_MASTER VALUES('24R45','LAPTOP',25,'KILO',165,7,32543.76,4546.65);
INSERT INTO PRODUCT_MASTER VALUES('42R45','MOBILE',20,'KG',100,8,564.56,415.96);
INSERT INTO PRODUCT_MASTER VALUES('25R45','TV',15,'INCHES',500,9,856.16,52.95);

-- Insert Salesmen with Client Reference
INSERT INTO SALESMAN_MASTER VALUES('CP020','RAHUL','TCS','NANDEL_CHOCK','RAJKOT',360005,'GUJARAT',62000.50,2555,7547,'GOOD','1Y093');
INSERT INTO SALESMAN_MASTER VALUES('CP071','HEER','MICROSOFT','KRISHNA_CHOCK','SURAT',352013,'GUJARAT',27000.50,2465,9568,'VERY_GOOD','12T53');
INSERT INTO SALESMAN_MASTER VALUES('CP001','KRISH','GOOGLE','RAJ_CHOCK','MUMBAI',384512,'MAHARASHTRA',3500,8655,5656,'EXCELLENT','56087');

------------------------------------------------------------
-- Step 3: Examples of Constraints
------------------------------------------------------------

-- 1) PRIMARY KEY: CLIENTNO is unique, duplicate insert will fail
-- INSERT INTO CLIENT_MASTER VALUES('1Y093','ANITA','ROAD','BLOCK','VADODARA',390001,'GUJARAT',500);

-- 2) UNIQUE: DESCRIPTION in PRODUCT_MASTER must be unique
-- INSERT INTO PRODUCT_MASTER VALUES('30R45','LAPTOP',18,'PCS',50,5,6000,4000); -- will fail

-- 3) NOT NULL: SALESMANNAME cannot be NULL
-- INSERT INTO SALESMAN_MASTER(SALESMANNO,SALESMANNAME) VALUES('CP099',NULL); -- will fail

-- 4) FOREIGN KEY with ON DELETE CASCADE
-- If CLIENT '1Y093' is deleted, SALESMAN with CLIENTNO '1Y093' will also be deleted
-- DELETE FROM CLIENT_MASTER WHERE CLIENTNO='1Y093';

------------------------------------------------------------
-- Step 4: Constraint with User-Defined Names
------------------------------------------------------------

-- Table with custom constraint names
CREATE TABLE ORDERS (
    ORDERNO INT CONSTRAINT PK_ORDER PRIMARY KEY,
    CLIENTNO VARCHAR(6),
    PRODUCTNO VARCHAR(6),
    CONSTRAINT FK_ORDER_CLIENT FOREIGN KEY (CLIENTNO)
        REFERENCES CLIENT_MASTER(CLIENTNO)
        ON DELETE SET NULL,
    CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY (PRODUCTNO)
        REFERENCES PRODUCT_MASTER(PRODUCTNO)
);

-- Insert Orders
INSERT INTO ORDERS VALUES(101,'12T53','42R45');
INSERT INTO ORDERS VALUES(102,'56087','25R45');

------------------------------------------------------------
-- End of Lab 5 SQL File
-- =========================================================
