CREATE TABLE CLIENT_MASTER (
    CLIENTNO VARCHAR(6) UNIQUE NOT NULL,
    NAME VARCHAR(7) UNIQUE NOT NULL,
    ADDRESS1 VARCHAR(30),
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(15),
    PINCODE NUMERIC(6),
    STATE VARCHAR(15),
    BALDUE NUMERIC(10,2)
);

INSERT INTO CLIENT_MASTER VALUES('1Y093','DARSHAN','SHASTRI MEDAIN','VIDYANAGAR','ANAND',360005,'GUJARAT',122.45);
INSERT INTO CLIENT_MASTER VALUES('12T53','HEER','GANDHI MEDAIN','GANDHINAGAR','AHMADABAD',387625,'TAMILNADU',950.45);
INSERT INTO CLIENT_MASTER VALUES('56087','KRISH','SHIVAM MEDAIN','PUNE','MUMBAI',282425,'MAHARASHTRA',91556.54);

SELECT * FROM CLIENT_MASTER;

CREATE TABLE PRODUCT_MASTER (
    PRODUCTNO VARCHAR(6),
    DESCRIPTION VARCHAR(15),
    PROFITPERCENT NUMERIC(4,2),
    UNITMEASURE VARCHAR(10),
    QTYONHAND NUMERIC(8),
    REORDERLVL NUMERIC(8),
    SELLPRICE NUMERIC(8,2),
    COSTPRICE NUMERIC(8,2)
);

INSERT INTO PRODUCT_MASTER VALUES('24R45','LAPTOP',25,'KILO',165,7,32543.76,4546.65);
INSERT INTO PRODUCT_MASTER VALUES('42R45','MOBILE',20,'KG',100,8,564.56,415.96);
INSERT INTO PRODUCT_MASTER VALUES('25R45','TV',15,'INCHES',500,9,856.16,52.95);

SELECT * FROM PRODUCT_MASTER;

CREATE TABLE SALESMAN_MASTER (
    SALESMANNO VARCHAR(6),
    SALESMANNAME VARCHAR(20),
    ADDRESS1 VARCHAR(30),
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(20),
    PINCODE NUMERIC(6),
    STATE VARCHAR(20),
    SALAMT NUMERIC(8,2),
    TGTTOGET NUMERIC(6,2),
    YTDSALES NUMERIC(6,2),
    REMARKS VARCHAR(60)
);

INSERT INTO SALESMAN_MASTER VALUES('CP020','DARSHAN','TCS','NANDEL_CHOCK','RAJKOT',360005,'GUJARAT',62000.50,2555,7547,'GOOD');
INSERT INTO SALESMAN_MASTER VALUES('CP071','HEER','MICROSOFT','KRISHNA_CHOCK','SURAT',352013,'GUJARAT',27000.50,2465,9568,'VERY_GOOD');
INSERT INTO SALESMAN_MASTER VALUES('CP001','KRISH','GOOGLE','RAJ_CHOCK','MUMBAI',384512,'MAHARASHTRA',3500,8655,5656,'EXCELLENT');

CREATE TABLE SALES_ORDER (
    ORDERNO     VARCHAR2(6) PRIMARY KEY,
    CLIENTNO    VARCHAR2(6) REFERENCES CLIENT_MASTER(CLIENTNO),
    ORDERDATE   DATE NOT NULL,
    DELYADDR    VARCHAR2(25),
    SALESMANNO  VARCHAR2(6) REFERENCES SALESMAN_MASTER(SALESMANNO),
    DELYTYPE    CHAR(1) DEFAULT 'F' CHECK (DELYTYPE IN ('P','F')),
    BILLYN      CHAR(1),
    DELYDATE    DATE CHECK (DELYDATE >= ORDERDATE),
    ORDERSTATUS VARCHAR2(10) CHECK (ORDERSTATUS IN ('In Process','Fulfilled','BackOrder','Cancelled'))
);

CREATE TABLE SALES_ORDER_DETAILS (
    ORDERNO     VARCHAR2(6) REFERENCES SALES_ORDER(ORDERNO),
    PRODUCTNO   VARCHAR2(6) REFERENCES PRODUCT_MASTER(PRODUCTNO),
    QTYORDERED  NUMBER(8),
    QTYDISP     NUMBER(8),
    PRODUCTRATE NUMBER(10,2),
    PRIMARY KEY (ORDERNO, PRODUCTNO)
);

--Queries--

1.
SELECT NAME
FROM CLIENT_MASTER
WHERE NAME LIKE '_a%';

2.
SELECT DESCRIPTION, SELLPRICE
FROM PRODUCT_MASTER
WHERE SELLPRICE > 500 AND SELLPRICE <= 750;

3.
SELECT P.DESCRIPTION, SUM(SD.QTYORDERED) AS TOTAL_QTY_SOLD
FROM PRODUCT_MASTER P
JOIN SALES_ORDER_DETAILS SD ON P.PRODUCTNO = SD.PRODUCTNO
GROUP BY P.DESCRIPTION;

4.
SELECT C.NAME, AVG(SD.QTYORDERED) AS AVG_QTY
FROM CLIENT_MASTER C
JOIN SALES_ORDER S ON C.CLIENTNO = S.CLIENTNO
JOIN SALES_ORDER_DETAILS SD ON S.ORDERNO = SD.ORDERNO
GROUP BY C.NAME
HAVING MAX(SD.QTYORDERED * SD.PRODUCTRATE) = 15000.00;

5.
SELECT DISTINCT P.DESCRIPTION
FROM PRODUCT_MASTER P
JOIN SALES_ORDER_DETAILS SD ON P.PRODUCTNO = SD.PRODUCTNO
JOIN SALES_ORDER S ON SD.ORDERNO = S.ORDERNO
JOIN CLIENT_MASTER C ON S.CLIENTNO = C.CLIENTNO
WHERE C.NAME = 'IVAN BAYROSS';

6.
SELECT P.DESCRIPTION, SUM(SD.QTYDISP) AS QTY_TO_DELIVER
FROM PRODUCT_MASTER P
JOIN SALES_ORDER_DETAILS SD ON P.PRODUCTNO = SD.PRODUCTNO
JOIN SALES_ORDER S ON SD.ORDERNO = S.ORDERNO
WHERE TO_CHAR(S.DELYDATE, 'MM-YYYY') = TO_CHAR(SYSDATE, 'MM-YYYY')
GROUP BY P.DESCRIPTION;

