
-- CLIENT_MASTER TABLE

CREATE TABLE CLIENT_MASTER (
    CLIENTNO VARCHAR(6) UNIQUE NOT NULL,
    NAME VARCHAR(7) UNIQUE NOT NULL,
    ADDRESS1 VARCHAR(30),
    ADDRESS2 VARCHAR(30),
    CITY VARCHAR(15),
    PINCODE NUMERIC(6),
    STATE VARCHAR(15),
    BALDUE NUMERIC(10,2)
);

INSERT INTO CLIENT_MASTER VALUES('1Y093','DARSHAN','SHASTRI MEDAIN','VIDYANAGAR','ANAND',360005,'GUJARAT',122.45);
INSERT INTO CLIENT_MASTER VALUES('12T53','HEER','GANDHI MEDAIN','GANDHINAGAR','AHMADABAD',387625,'TAMILNADU',950.45);
INSERT INTO CLIENT_MASTER VALUES('56087','KRISH','SHIVAM MEDAIN','PUNE','MUMBAI',282425,'MAHARASHTRA',91556.54);

ALTER TABLE CLIENT_MASTER RENAME COLUMN CLIENTNO TO CLIENT;

SELECT * FROM CLIENT_MASTER;
SELECT NAME FROM CLIENT_MASTER;
SELECT NAME, CITY, STATE FROM CLIENT_MASTER;
SELECT NAME FROM CLIENT_MASTER WHERE CITY = 'MUMBAI';

UPDATE CLIENT_MASTER SET CITY = 'BANGALORE' WHERE CLIENT = '1Y093';
UPDATE CLIENT_MASTER SET BALDUE = 1000 WHERE CLIENT = '12T53';

DELETE FROM CLIENT_MASTER WHERE STATE = 'TAMILNADU';

ALTER TABLE CLIENT_MASTER ADD COLUMN TELEPHONE NUMERIC(10);
ALTER TABLE CLIENT_MASTER RENAME TO CLI_MAST;

-- SELECT * FROM CLI_MAST;
